---
- hosts: local
  connection: local
  gather_facts: no
  vars:
    region: ap-south-1
    keyname: infra-test
    secutiy_grp_name: infra_test_sg
    instance_type: t2.micro
    image: ami-5b673c34

  tasks:

    # Create EC2 keypair
    - name: create keypair
      tags: keypair
      ec2_key:
        region: "{{ region }}"
        name: "{{ keyname }}"
      register: created_key

    # save key to local FS
    - name: save key to filesystem
      copy: content="{{ created_key.key.private_key }}" dest="~/.ssh/{{keyname }}.pem" mode=0600
      when: created_key.changed

    - name: create security group
      tags: sg
      ec2_group:
        name: "{{ secutiy_grp_name }}"
        region: "{{ region }}"
        description: Testing Infrastructre SQG
        rules:
          # SSH access
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          # http access
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          # https access
          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0

    # create ec2 instance
    - name: create ec2 instance
      tags: ec2
      ec2:
        region: "{{ region }}"
        instance_type: "{{ instance_type }}"
        key_name: "{{ keyname }}"
        image: "{{ image }}"
        wait: yes
        group: "{{ secutiy_grp_name }}"
        instance_tags:
          Name: infra-test-jenkins
      register: ec2

    #- name: assign eip to instance
    #  ec_eip:
    #    region: "{{ region }}"
    #    instance_id: "{{ item.id }}"
    #  with_items: ec2.instances
    #  when: item.id is defined
