---
# ssh config
ansible_ssh_user: ec2-user
ansible_ssh_private_key_file: ~/.ssh/ap-south-1-test.pem

# Provision config
envrmnt: test
region: ap-south-1
provison_config: "{{ lookup('file', 'provison_config.json') | from_json }}" 