- name: create ec2 key pair
  tags: keypair
  ec2_key:
    region: "{{ aws-region }}"
    name: "{{ aws-region }}_{{ environment }}"
  register: created_key

- name: save key to filesystem
  copy: content="{{ created_key.key.private_key }}" dest="~/.ssh/{{ aws-region }}_{{ environment }}.pem" mode=0600
  when: created_key.changed
  
- name: create security group
  tags: security_group
  ec2_group:
    name: "{{ aws-region }}_{{ environment }}_sg"
    region: "{{ aws-region }}"
    description: "{{ environment }} SG"
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0          
      - proto: tcp
        from_port: 443
        to_port: 443
        cidr_ip: 0.0.0.0/0
    rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0

- name: create ec2 instances
  tags: ec2
  ec2:
    region: "{{ aws-region }}" 
    instance_type: "{{ item.instance_type }}"
    key_name: "{{ aws-region }}_{{ environment }}"
    image: "{{ item.image }}"
    group: "{{ aws-region }}_{{ environment }}_sg"
    wait: yes
    instance_tags:
      Name: "{{ item.name }}"
    count_tag:
      Name: "{{ item.name }}"
    exact_count: 1
  with_items: "{{ provison_config }}"
